### ISSUE TITLE
Scoreboard colors from former group not being cloned properly.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#335]
Paper dev 507 (Spigot 1.13.2)
LibsDisguise dev 255
NameTagEdit dev 48

@libraryaddict LibsDisguise does not seem to be cloning the scoreboard group the player is assigned to properly. The name on hover is always white -- tested with both IGNORE_SCOREBOARD and CREATE_SCOREBOARD. Intended behavior is trying to retain the color of the player's name when hovering over the disguise.

![link](https://i.imgur.com/RugrMEI.jpg)
![link](https://i.imgur.com/rkrbo6J.jpg)

Undisguising, the player is back to pink.

```
# How should the plugin handle self disguises scoreboards? It disables pushing in whichever team they're assigned.
# If you want them to be able to push again when they undisguise, set this to CREATE_SCOREBOARD
# I have to disable pushing or you will be pushed around by your own self disguise
# MODIFY_SCOREBOARD - Modifies the player's current team if possible, otherwise assigns them to a new scoreboard team.
# IGNORE_SCOREBOARD - Doesn't touch scoreboards at all, effectively means that if you didn't disable pushing in their scoreboard team; They will still be pushed around
# CREATE_SCOREBOARD - Creates a new team which copies the attributes of their previous scoreboard team which they are then assigned to. This means they keep nametag color and other options.
SelfDisguisesScoreboard: CREATE_SCOREBOARD

# More options in case you want to disable a specific setting of the scoreboard
Scoreboard:
  # Should it modify the scoreboard to turn collisions off?
  Collisions: true
  # Should it modify the scoreboard teams to disable seeing friendly invisibles?
  DisableFriendlyInvisibles: true
  # Should the scoreboard warn you if it detects a potential conflict?
  # If self disguises are disabled, or the scoreboard is using IGNORE_SCOREBOARD then this does nothing.
  WarnConflict: true
```
```
# This is only called into action when the disguise is constructed using the commands.
# And when the disguise supports that. This will not be used at all for plugins constructing the disguises for instance.
# Such as prophunt. Its also false because its kind of a retarded feature.
# This is pretty simple. It shows the players displayname (Name as it appears in chat) above their head.
# This also overrides any custom name they have set in their disguise options.
# This does not take effect on player disguises
ShowNamesAboveDisguises: true

# This supports the above option.
# If this is true, then the name shown above the head appears regardless of if you are looking at the disguise directly or not.
NameAboveHeadAlwaysVisible: false
```

--

I am using the plugin NameTagEdit to set their displayname colors based on their primary group prefix.

```
Groups:
  Player:
    Permission: nte.player 
    Prefix: '%vault_prefix%'
    Suffix: '&f'
```

NTE config
https://paste.ubuntu.com/p/bHx44n8vzV/
