### ISSUE TITLE
Extended Names nameplate changing

### ISSUE THREAD

**Issue by UltraFaceguy** [libraryaddict/LibsDisguises#423]
Names seemed to be working, but can sometimes... flicker? And display the wrong name? It should be noted that the entity is the correct name, but the nameplate is... interesting. As seen in the screens below, the 'Dark Knight' mob gets the 'Highwayman' name, which is for an unrelated entity not seen in the image. Also it random changes their name to "&7L"

Including small code and config sample to show usage, in case that helps at all 🤷‍♂ 

Using build # 370

```
if (type == DisguiseType.PLAYER) {
      String disguisePlayer = section.getString("disguise-player");
      if (StringUtils.isBlank(disguisePlayer)) {
        disguisePlayer = "Notch";
      }
      PlayerDisguise playerDisguise = new PlayerDisguise(name, disguisePlayer);
      playerDisguise.setReplaceSounds(true);
      return playerDisguise;
    }
```
```
highwayman:
  type: SKELETON
  name: "Highwayman &7Lv21"
  base-level: 21
  bonus-experience: 100
  knockback-immune: false
  burn-immune: true
  disguise:
    type: PLAYER
    disguise-player: "Captainturtl"
darkknight:
  type: ZOMBIE
  name: "Dark Knight &7Lv42"
  base-level: 42
  experience-multiplier: 1.2
  bonus-experience: 5
  follow-range: 8
  remove-range-modifiers: true
  knockback-immune: false
  burn-immune: true
  disguise:
    type: PLAYER
    disguise-player: "ZakMckracken"
```

![2020-01-21_15 29 34](https://user-images.githubusercontent.com/1491435/72840768-f601dc00-3c62-11ea-8291-529ed018ff74.png)
![2020-01-21_15 29 35](https://user-images.githubusercontent.com/1491435/72840769-f7330900-3c62-11ea-8799-5c70026e3f6a.png)
