### ISSUE TITLE
Disguises stop colored glow from working

### ISSUE THREAD

**Issue by HexedHero** [libraryaddict/LibsDisguises#637]
Using MythicMobs as a test

**TestMobs.yml**
```
Color:
  Type: ZOMBIE
  Skills:
    - effect:glow{color=RED;duration=1000} ~onTimer:20 @self

NoColor:
  Type: ZOMBIE
  Disguise: SKELETON
  Skills:
    - effect:glow{color=RED;duration=1000} ~onTimer:20 @self
```

Spawning the mob called Color will make them glow red while the mob called NoColor will glow the default white.
The glow uses GlowAPI and this wasn't the case and works in previously LibsDisguises versions such as v10.0.24, the same setup on 1.16.5 with v10.0.24 works, then switching to 10.0.27 in the same setup breaks the colors.

Plugins (5): GlowAPI, LibsDisguises, MythicMobs, PacketListenerApi, ProtocolLib

GlowAPI version 1.5.2-SNAPSHOT
LibsDisguises version 10.0.27
MythicMobs version 5.0.0-SNAPSHOT-b2823337
PacketListenerApi version 3.9.9-SNAPSHOT
ProtocolLib version 4.8.0-SNAPSHOT-b540

This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are running the latest version
