### ISSUE TITLE
Lost displayname colors in disguised mobs

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [libraryaddict/LibsDisguises#758]
Hi,
I'm testing your 0.4.1 PacketEvents version with MythicMobs and encountered this issue on 1.20.6 version.

I'm using this configuration within MythicMobs:
```
PROKURATOR:
  Type: husk
  Health: 10
  Damage: 2
  Display: "<red><caster.hp{round=2}> <&heart> <dark_gray>| <dark_purple>Prokurator <dark_gray>(<gray>poz. <caster.level><dark_gray>)"
  LevelModifiers:
    Health: 1.5
    Damage: 0.2
  AIGoalSelectors:
    - meleeattack
    - randomstroll
    - goToSpawn{speed=1;max=10;min=3}
  AITargetSelectors:
    - clear
    - players
  Skills:
    - setname{name=<caster.name>;delay=2} @self ~onDamaged
    - setname{name=<caster.name>;delay=2} @self ~onTimer:20
    - potion{type=INCREASE_DAMAGE;level=2;duration=2400} @target
  Options:
    Despawn: persistent
    PreventSunburn: true
    PreventJockeyMounts: true
    AlwaysShowName: true
  Disguise: PORZADKOWA
  ```
  
and every second (on timer) mob name is getting coloured and then without any colors. It happens only for disguised mobs

https://github.com/libraryaddict/LibsDisguises/assets/13908095/5c4e9fb1-a57f-4833-bd04-a904b7a8d3b3

my disguises.yml is set to
```
  PORZADKOWA: player <inherit> setskin {"id":"1e6f175d-544e-4040-a3cd-e54d8f3520ad","properties":[{"name":"textures","value":"ewogICJ0aW1lc3RhbXAiIDogMTYwOTMzMzE2MjY0MywKICAicHJvZmlsZUlkIiA6ICJlZDUzZGQ4MTRmOWQ0YTNjYjRlYjY1MWRjYmE3N2U2NiIsCiAgInByb2ZpbGVOYW1lIiA6ICI0MTQxNDE0MWgiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTM0YjY1OTlkMDQ0MTkyZjVkY2RjZWJkZDMzMzQ0NTliZTM2YzI3ZjMwZGU0YzRlNThlYTdhYTIzZjQxYWU4OCIKICAgIH0KICB9Cn0=","signature":"RL5kX6eOaDSOtSCVxWcBvILiLZwzibBaQ9aZIEEXF+hHyFD/ZbXNFYczxoE2lfxZweJZiGTkmMypXk09KDAHx9IGdicGzL9xKT6uLIEfq9qbDgEKmgnNeKDVy8WBNFyFjMaTpHxDniHeHxxCmzouYsSe07N8clOqWI9Zs8eHvnTqtF5rEomQET7SvbqHSUWl7JhpLShFOOpYwRF1Cqx79vO+qo8foaaY55ko/2FhwMBGmj5z9N+vWyx572dJdUH+FtsznpUD4POFA58MA+M9Pg6p+VQHuhLHVY5RoPO/zN20uqWfLBKr4I7dGHH1eGhC4FOlm1qeZEsevAVS/7ou18HDIkznw8vlFBDNg+ZoV02lPFs4nNqJ1rhZ6+OWcYP6Fxw+u1xoqAJOVfz8igaa7pKCePpi7T24iCXt95u1Jc8u45V6ftdAQvrwCAtDvDwXw4XIg3T8igu5oRsMX/Y+pIQRSr0PCq/Pmy1Ofr8drpsrKcn2lTiqKAUKPGT1AINf8IABmYkSP1fevkrAwmA26yZqB05snylCKKigCbIVxxXPF71SKF5qcyfDFKj5xYTGwnlhkmhPQKx8A+RdRsHo3aVtZ75Zj9rXWC3AywFfvWmQcZfY0OKFn44zSvYgHzBOq1tEq7Kqg7V7hSutQk6XbCKMoElS7X1gWfP+EsymGtg="}],"legacy":false}
    setDynamicName
```
