### ISSUE TITLE
Transparent skin becomes black

### ISSUE THREAD

**Issue by Evalutik** [libraryaddict/LibsDisguises#759]
I am trying to create a "ghost" using transparant skin:
![MazeGuard2](https://github.com/libraryaddict/LibsDisguises/assets/126126362/91bf3101-b9e5-44b4-9108-bd563ee8970a)

Iam using `/savedisguise MazeGuard player <inherit> setSkin MazeGuard2.png` to create MazeGuard disguise.

In MM mob config file i am using: `Disguise: MazeGuard`

But after this what i see is 
![image](https://github.com/libraryaddict/LibsDisguises/assets/126126362/24f6c40e-3341-4f72-b4e9-ece19bf0e722)

So, transparant parts of skin become black.

How to fix? Or, if not, how to make visible nametag + invisible mob, so i can leave only "flying" armor? 

 configs\nametags.yml:
[nametags.txt](https://github.com/user-attachments/files/15958972/nametags.txt)

MM mob:

```
MazeGuard:
  Type: ZOMBIE
  Display: '&f%math_1:_<caster.hp>%&4❤'
  Health: 50
  Damage: 8
  Equipment:
  - IRON_HELMET HEAD
  - IRON_CHESTPLATE CHEST
  - STONE_SWORD HAND
  Skills:
  - setname{name=<caster.name>;delay=2} @self ~onDamaged
  - potion{type=SLOW;duration=200;level=3} @target ~onAttack 1
  - effect:particles{particle=redstone;amount=50;color=#808080;hS=0.4;vS=0.8;speed=2} @target ~onAttack
  Options:
    MovementSpeed: 0.35
    KnockbackResistance: 0.4
    AlwaysShowName: false
    HealOnReload: true
    PreventSunburn: true
    MaxCombatDistance: 16
  Modules:
    ThreatTable: true
  Disguise: MazeGuard
```

Server version: PurPur: 1.20.2
Lib's Disguises version: 10.0.44
MM version: 5.6.2
ProtocolLib version: v5.1.1-SNAPSHOT-673
