### ISSUE TITLE
Name Above Head Always Visible not working for players

### ISSUE THREAD

**Issue by Evalutik** [libraryaddict/LibsDisguises#760]
I am trying to create a disguise with type player. I need to name of the mob will be visible only while looking on it.

Iam using `/savedisguise MazeGuard player <inherit> setSkin MazeGuard2.png setDynamicName true setCustomNameVisible false` to create MazeGuard disguise. 

In MM mob config file i am using: `Disguise: MazeGuard`

But after this name tag of the mob just permanently invisible. If i instead use  `/savedisguise MazeGuard player <inherit> setSkin MazeGuard2.png setDynamicName true setCustomNameVisible true` and apply it, name tag will be just permanently visible. It all works correctly with mob type disguise: `Disguise: skeleton setDynamicName true setCustomNameVisible false`, but not with a player type.

In the  configs\nametags.yml i have 
`ShowNamesAboveDisguises: true`
and
`NameAboveHeadAlwaysVisible: false`

but i didnt notice any changes, while changing this.

I also have `PlayerNames: 'ARMORSTANDS'`

My configs\nametags.yml:
[nametags.txt](https://github.com/user-attachments/files/15958827/nametags.txt)

MM mob:

```
MazeGuard:
  Type: ZOMBIE
  Display: '&f%math_1:_<caster.hp>%&4❤'
  Health: 50
  Damage: 8
  Equipment:
  - IRON_HELMET HEAD
  - IRON_CHESTPLATE CHEST
  - STONE_SWORD HAND
  Skills:
  - setname{name=<caster.name>;delay=2} @self ~onDamaged
  - potion{type=SLOW;duration=200;level=3} @target ~onAttack 1
  - effect:particles{particle=redstone;amount=50;color=#808080;hS=0.4;vS=0.8;speed=2} @target ~onAttack
  Options:
    MovementSpeed: 0.35
    KnockbackResistance: 0.4
    AlwaysShowName: false
    HealOnReload: true
    PreventSunburn: true
    MaxCombatDistance: 16
  Modules:
    ThreatTable: true
  Disguise: MazeGuard
```

How to fix?

Server version: PurPur: 1.20.2
Lib's Disguises version: 10.0.44
MM version: 5.6.2
ProtocolLib version: v5.1.1-SNAPSHOT-673
