### ISSUE TITLE
PacketEvent

### ISSUE THREAD

**Issue by CesarSanchezGomez** [libraryaddict/LibsDisguises#778]
server: purpur-1.21
plugin: CustomFishing 2.2.30
LibsDisguise 10.0.44-SNAPSHOT Premium

Hi, I've been setting up items for Halloween with the CustomFishing plugin, and I encountered a small issue when configuring items with food components and holding them in hand, related to LibsDisguise. A very long WARN message starts spamming in the server console. I'm attaching the configuration of the item in question and the warning.

Item:

```
Gragea_de_malvavisco_t:
  tag: false
  material: potato
  custom-model-data: 50001
  display:
    name: "<white>🎃 </white><gradient:#FFFFFF:#BDBDBD>Gragea de malvavisco</gradient><white> 🎃</white>"
    lore:
      - "&f"
      - "<white>[</white><gradient:#FFFFFF:#BDBDBD> ⊰ ⋪ ⊱ <white>] ¿Dulce o truco? [</white> ⊰ ⋫ ⊱ </gradient><white>]</white>"
      - "&f"
      - ""
  components:
    minecraft:food:
      nutrition: 1
      saturation: 0.6
      can_always_eat: true
      eat_seconds: 2
      effects:
        - effect: 
            id: minecraft:invisibility
            amplifier: 0
            duration: 1800
          probability: 0.5
  disable-game: true
  disable-stat: true
```

WARN: [PacketEvent](https://pastebin.com/9Hyu4CWJ)
